[package]
name = "nvidia-fan-control-rs"
version = "0.1.0"
authors = ["fabio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = ""
ctrlc = ""
